import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { getClaimWorkspace } from "@/lib/data/claims";
import { formatMoney, formatMonth } from "@/lib/utils";
import type { InvoiceCategory } from "@/lib/types";

export const runtime = "nodejs";

export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const workspace = await getClaimWorkspace(id);
  if (!workspace) return Response.json({ error: "Claim not found" }, { status: 404 });

  const document = await PDFDocument.create();
  const regular = await document.embedFont(StandardFonts.Helvetica);
  const bold = await document.embedFont(StandardFonts.HelveticaBold);
  let page = document.addPage([612, 792]);
  let y = 744;
  const ink = rgb(0.08, 0.12, 0.16);
  const muted = rgb(0.38, 0.43, 0.48);
  const green = rgb(0.05, 0.55, 0.38);

  const line = (text: string, size = 10, font = regular, color = ink, indent = 0) => {
    if (y < 54) {
      page = document.addPage([612, 792]);
      y = 744;
    }
    page.drawText(text.slice(0, 105), { x: 48 + indent, y, size, font, color });
    y -= size + 8;
  };

  line("FERN CLAIMS PROCESS", 10, bold, green);
  line(`${workspace.claim.company.name} · ${formatMonth(workspace.claim.period_month)}`, 20, bold);
  line(`Claim status: ${workspace.claim.status.toUpperCase()}`, 10, bold, muted);
  y -= 8;
  line("EXECUTIVE EXPENDITURE SUMMARY", 11, bold);
  line(`Total claimed: ${formatMoney(Number(workspace.summary?.total_amount ?? 0))}`, 16, bold);
  for (const category of ["software", "ads", "office", "other"] as InvoiceCategory[]) {
    line(`${category[0].toUpperCase()}${category.slice(1)}: ${formatMoney(Number(workspace.summary?.category_totals?.[category] ?? 0))}`, 10, regular, ink, 12);
  }
  line(`Unmatched statement charges: ${workspace.summary?.unmatched_count ?? workspace.statementItems.filter((item) => !item.matched).length}`, 10, bold);
  if (workspace.summary?.variance_notes) line(workspace.summary.variance_notes, 9, regular, muted, 12);
  y -= 10;
  line("INVOICES", 11, bold);
  for (const invoice of workspace.invoices) {
    line(`${invoice.invoice_date}  ${invoice.vendor}  ·  ${invoice.category}  ·  ${formatMoney(Number(invoice.amount), invoice.currency)}  ·  ${invoice.match_status}`, 9);
  }
  y -= 8;
  line("UNMATCHED CARD CHARGES", 11, bold);
  const unmatched = workspace.statementItems.filter((item) => !item.matched);
  if (!unmatched.length) line("None — every charge in this period is reconciled.", 9, regular, muted);
  for (const item of unmatched) {
    line(`${item.transaction_date}  ${item.merchant}  ·  ${formatMoney(Number(item.amount), item.currency)}`, 9);
  }
  y -= 14;
  line("Generated by Fern Claims Process", 8, regular, muted);

  const bytes = await document.save();
  const filename = `${workspace.claim.company.name}-${workspace.claim.period_month}-claim.pdf`
    .toLowerCase()
    .replace(/[^a-z0-9.-]+/g, "-");
  return new Response(Buffer.from(bytes), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "no-store",
    },
  });
}
